### ISSUE TITLE
The road to 1.0

### ISSUE THREAD

**Issue by mheap** [mheap/trello-cli#33]
@ksk100 @vinyldarkscratch As the two largest contributors so far, how would you like to weigh in on `trello-cli` 1.0? At the moment there aren't any established coding guidelines, there aren't any tests (though there is a start on https://github.com/mheap/trello-cli/tree/testing-infra) and the output format could change between releases, breaking existing user's scripts. On top of all of that, the only way to use `trello-cli` at the moment is to build from Github as the one on NPM is so outdated.

So, the plan is to:

- [x] Publish version 0.5 on NPM
- [x] Set up ESLint rules for the project
- [x] Add automated TravisCI builds
- [ ] Add tests for existing output so that we can maintain backwards compatibility where possible

I'll also be looking for some example use cases, so if you have anything that you'd like to share, please let me know

**Comment by vinyldarkscratch** [comment]
Yeah, I'd definitely be interested in helping out, thank you for the invitation!  I am not the most familiar with NPM (actually, this is the first Node.js project I've contributed to) and ESLint, but I have some experience with TravisCI.  😉  I also have a list of features that my programming mentor (partner?) and I have been planning on -- you guessed it -- a Trello board, and can add both of you (or anyone who wishes to help out) to it, possibly make it our planned feature list if desired?

Also, that programming mentor/partner I mentioned, would you be willing to add him, @mglover, as well?  The two of us are actually working on our fork together (currently from afar through the help of IRC), and without him, I wouldn't have been able to work on this project!

**Comment by mheap** [comment]
Of course! The more people involved, the merrier :) I'd love to see the plan that both yourself and @mglover have put together

**Comment by vinyldarkscratch** [comment]
Thank you very much, I appreciate it!  😄  I just got a bunch set up on my end, and was playing around with NPM a little bit to figure out how to operate it.  Kudos to Node for how easy it is to publish packages!  I reduced the version number to 0.0.5 (instead of 0.1.0, which I set mainly since there's quite a few changes since 0.0.4 that might make merging a little difficult), and I'm going to be making sure that dependencies are all accurate, ready for you to publish.  ;)  (I just signed up for an NPM account (same username as here on GitHub) and found out that I can't publish because I don't have the rights to do so...  Of course I don't.  XD)

Also, if you would like to see the feature list that @mglover and I have planned, I added those four pieces you had put up above and put the list on a new Trello board for anyone to see: https://trello.com/b/vekjgwTN

**Comment by ksk100** [comment]
Hey,

Thanks for the invitation and update.  I'm still using trello-cli, but at
the moment I'm not so much in a position to help out too much more.

Really sorry, but looking forward to seeing more of all the dev that is
going on with it

Am 29.12.2016 19:39 schrieb "Michael Heap" <notifications@github.com>:

@ksk100 <https://github.com/ksk100> @vinyldarkscratch
<https://github.com/vinyldarkscratch> As the two largest contributors so
far, how would you like to weigh in on trello-cli 1.0? At the moment there
aren't any established coding guidelines, there aren't any tests (though
there is a start on https://github.com/mheap/trello-cli/tree/testing-infra)
and the output format could change between releases, breaking existing
user's scripts. On top of all of that, the only way to use trello-cli at
the moment is to build from Github as the one on NPM is so outdated.

So, the plan is to:

   - Publish version 0.5 on NPM
   - Set up ESLint rules for the project
   - Add automated TravisCI builds
   - Add tests for existing output so that we can maintain backwards
   compatibility where possible

I'll also be looking for some example use cases, so if you have anything
that you'd like to share, please let me know

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/mheap/trello-cli/issues/33>, or mute the thread

**Comment by vinyldarkscratch** [comment]
Hey Simon, that makes complete sense, yeah -- thank you for your contributions already, I personally was able to work off of it well!  Happy New Years to you, and hope all goes well.  :)

- Vinyl Darkscratch-Kazotetsu, Founder of Nightwave Studios
(Sent from my Nightinfection, my iPhone)

--
If you believe you have received this email in error, please contact me at vinyldarkscratch@gmail.com, Twitter @vdscratchy, or Skype at vinyldarkscratch

**Comment by mheap** [comment]
@vinyldarkscratch Could you add me to the board? I'm "michaelheap" on Trello

**Comment by vinyldarkscratch** [comment]
But of course!  Adding you right away, one moment.  ;)

- Vinyl Darkscratch-Kazotetsu, Founder of Nightwave Studios
(Sent from my Nightinfection, my iPhone)

--
If you believe you have received this email in error, please contact me at vinyldarkscratch@gmail.com, Twitter @vdscratchy, or Skype at vinyldarkscratch

**Comment by vinyldarkscratch** [comment]
And, added!

- Vinyl Darkscratch-Kazotetsu, Founder of Nightwave Studios
(Sent from my Nightinfection, my iPhone)

--
If you believe you have received this email in error, please contact me at vinyldarkscratch@gmail.com, Twitter @vdscratchy, or Skype at vinyldarkscratch
