### ISSUE TITLE
minor: after npm install, package-lock.json is always with git status "modified"

### ISSUE THREAD

**Issue by work67** [mheap/trello-cli#79]
This is minor but still:
When I do new install: git clone + npm install
or update: git pull + rm node_modules + "npm install"

I always get several little modifications in package-lock.json, so git status is never clean.

Can this be fixed somehow?
Maybe a better build process/scripts will solve it?
Or am I doing sth wrong?

I think this is easily  reproducible, so I won't post the diff.

Cheers!

**Comment by work67** [comment]
While we're at it - what is the recommended git + npm procedure to do trello-cli UPDATE?

**Comment by mheap** [comment]
@work67 At one point I had manually edited `package-lock.json` to fix a vulnerability in a dependency, but that issue was resolved.

I've just done a fresh clone and run `npm install` and the file hasn't changed for me. Could you check again?

I should update the README to say run `npm ci` rather than `npm install` so that it always reads the lock file.

RE: Recommended way to install and update is to install with `npm install -g trello-cli` rather than running from source

**Comment by work67** [comment]
@mheap :
doing:
1. git pull + npm install = git status ALL OK
2. git pull + npm ci = ALL OK
3. git clone + npm ci = all ok
4. git clone + npm install = all ok
5. what's more - diff-ing npm ci VS npm install  - gives completely same node_modules dir - probably obvious - but still was interesting to test.

Thanks for pointing out that `npm install -g trello-cli` is the best way to install.
I think I'm/was using git clone + npm install way - because I needed to tinker with the code a bit.

And in the README - the INSTALL / 'Using trello-cli' sections say different things.
The README needs a bit of clarification in the USAGE section.

This case can now be closed - as npm install does not make the package lock json file modified any more. Thanks!
